export const cars = [
  {
    id: 1,
    name: 'DACIA DUSTER',
    date: '24/10/2020',
    price: '180 000 DH',
    location: 'CASA',
    cityName: 'Casablanca',
    postalCode: '20000',
    seller: 'Particulier',
    image: 'https://content.presspage.com/uploads/1896/1920_18c0130-03.jpg?10000',
    type: 'SUV/4X4',
    details: [
      { label: '08/2019', value: '' },
      { label: '130 000 Km', value: '' },
      { label: 'Occasion', value: '' },
      { label: '15 CV', value: '' },
      { label: 'Consommation', value: '4,5/100 Km' },
      { label: 'Gris', value: '' },
      { label: 'Boite manuelle', value: '' },
      { label: '350 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Hybride (diesel / électrique)', value: '' },
      { label: 'Matricule', value: 'H 72' },
      { label: 'Jantes', value: '12' },
    ],
    rating: 5,
    actions: ['eye', 'p', 'exchange'],
  },
  {
    id: 2,
    name: 'RENAULT CLIO',
    date: '25/10/2020',
    price: '130 000 DH',
    location: 'RABAT',
    cityName: 'Rabat',
    postalCode: '10000',
    seller: 'Particulier',
    image: 'https://www.largus.fr/images/styles/max_1300x1300/public/images/renault-clio-alpine-line-blue-parts-1280x853-wm.jpg?itok=gSw7U9DJ',
    type: 'CITADINE',
    details: [
      { label: '08/2019', value: '' },
      { label: '130 000 Km', value: '' },
      { label: 'Occasion', value: '' },
      { label: '15 CV', value: '' },
      { label: 'Consommation', value: '4,5/100 Km' },
      { label: 'Gris', value: '' },
      { label: 'Boite automatique', value: '' },
      { label: '350 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Hybride (diesel / électrique)', value: '' },
      { label: 'Matricule', value: 'H 72' },
      { label: 'Jantes', value: '12' },
    ],
    rating: 5,
    actions: ['eye', 'p', 'exchange'],
  },
  {
    id: 3,
    name: 'AUDI A1 SPORTBACK',
    date: '26/10/2020',
    price: '500 000 DH',
    location: 'CASA',
    cityName: 'Casablanca',
    postalCode: '20000',
    seller: 'Particulier',
    image: 'https://image.elite-auto.fr/visuel/AUDI/audi_24a1sportbackadvhb2fbfr_angularfront.png',
    type: 'BERLINE',
    details: [
      { label: '08/2012', value: '' },
      { label: '130 000 Km', value: '' },
      { label: 'Neuf', value: '' },
      { label: '15 CV', value: '' },
      { label: 'Consommation', value: '4,5/100 Km' },
      { label: 'Gris', value: '' },
      { label: 'Boite manuelle', value: '' },
      { label: '350 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Hybride (diesel / électrique)', value: '' },
      { label: 'Matricule', value: 'H 72' },
      { label: 'Jantes', value: '12' },
    ],
    rating: 4,
    actions: ['eye', 'p', 'exchange'],
  },
    {
    id: 4,
    name: 'PEUGEOT 3008',
    date: '27/10/2020',
    price: '210 000 DH',
    location: 'TANGER',
    cityName: 'Tangier',
    postalCode: '90000',
    seller: 'Particulier',
    image: 'https://res.cloudinary.com/dkugkfusy/image/upload/w_2000/v1742308132/cars/models/urio2ud2xvplsheztahw.png',
    type: 'SUV/4X4',
    details: [
      { label: '05/2021', value: '' },
      { label: '85 000 Km', value: '' },
      { label: 'Occasion', value: '' },
      { label: '12 CV', value: '' },
      { label: 'Consommation', value: '5,0/100 Km' },
      { label: 'Blanc', value: '' },
      { label: 'Boite automatique', value: '' },
      { label: '180 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Diesel', value: '' },
      { label: 'Matricule', value: 'A 45' },
      { label: 'Jantes', value: '17' },
    ],
    rating: 5,
    actions: ['eye', 'p', 'exchange'],
  },
  {
    id: 5,
    name: 'VOLKSWAGEN GOLF 7',
    date: '28/10/2020',
    price: '195 000 DH',
    location: 'MARRAKECH',
    cityName: 'Marrakech',
    postalCode: '40000',
    seller: 'Particulier',
    image: 'https://cdn.autobip.com/400/photos/car_editions/3148.webp',
    type: 'COMPACTE',
    details: [
      { label: '11/2018', value: '' },
      { label: '110 000 Km', value: '' },
      { label: 'Occasion', value: '' },
      { label: '10 CV', value: '' },
      { label: 'Consommation', value: '4,2/100 Km' },
      { label: 'Noir', value: '' },
      { label: 'Boite manuelle', value: '' },
      { label: '150 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Diesel', value: '' },
      { label: 'Matricule', value: 'B 66' },
      { label: 'Jantes', value: '16' },
    ],
    rating: 4,
    actions: ['eye', 'p', 'exchange'],
  },
  {
    id: 6,
    name: 'HYUNDAI I10',
    date: '29/10/2020',
    price: '85 000 DH',
    location: 'FES',
    cityName: 'Fes',
    postalCode: '30000',
    seller: 'Particulier',
    image: 'https://www.hyundai.com/content/dam/hyundai/ma/fr/images/test/TEST2/1120X600-5.png',
    type: 'CITADINE',
    details: [
      { label: '01/2022', value: '' },
      { label: '35 000 Km', value: '' },
      { label: 'Neuf', value: '' },
      { label: '6 CV', value: '' },
      { label: 'Consommation', value: '5,5/100 Km' },
      { label: 'Rouge', value: '' },
      { label: 'Boite manuelle', value: '' },
      { label: '80 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Essence', value: '' },
      { label: 'Matricule', value: 'C 23' },
      { label: 'Jantes', value: '14' },
    ],
    rating: 3,
    actions: ['eye', 'p', 'exchange'],
  },
  {
    id: 7,
    name: 'BMW SÉRIE 3',
    date: '30/10/2020',
    price: '450 000 DH',
    location: 'CASA',
    cityName: 'Casablanca',
    postalCode: '20000',
    seller: 'Particuliel',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9tuDcvd7-QJz_W3XnP9fFYsdDGIHhG5cLVg&s',
    type: 'BERLINE',
    details: [
      { label: '09/2017', value: '' },
      { label: '90 000 Km', value: '' },
      { label: 'Occasion', value: '' },
      { label: '18 CV', value: '' },
      { label: 'Consommation', value: '6,0/100 Km' },
      { label: 'Bleu', value: '' },
      { label: 'Boite automatique', value: '' },
      { label: '250 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Diesel', value: '' },
      { label: 'Matricule', value: 'D 11' },
      { label: 'Jantes', value: '18' },
    ],
    rating: 5,
    actions: ['eye', 'p', 'exchange'],
  },
  {
    id: 8,
    name: 'TOYOTA COROLLA',
    date: '31/10/2020',
    price: '230 000 DH',
    location: 'RABAT',
    cityName: 'Rabat',
    postalCode: '10000',
    seller: 'Particulier',
    image: 'https://bucket.dealervenom.com/copeland-toyota/C430752_8X8_Front.webp?auto=compress%2Cformat&ixlib=php-3.3.1',
    type: 'BERLINE',
    details: [
      { label: '04/2020', value: '' },
      { label: '60 000 Km', value: '' },
      { label: 'Occasion', value: '' },
      { label: '9 CV', value: '' },
      { label: 'Consommation', value: '3,5/100 Km' },
      { label: 'Argent', value: '' },
      { label: 'Boite automatique', value: '' },
      { label: '122 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Hybride (essence / électrique)', value: '' },
      { label: 'Matricule', value: 'E 33' },
      { label: 'Jantes', value: '16' },
    ],
    rating: 4,
    actions: ['eye', 'p', 'exchange'],
  },
  {
    id: 9,
    name: 'FORD FIESTA',
    date: '01/11/2020',
    price: '115 000 DH',
    location: 'AGADIR',
    cityName: 'Agadir',
    postalCode: '80000',
    seller: 'Particulier',
    image: 'https://bucket.dealervenom.com/copeland-toyota/C430752_8X8_Front.webp?auto=compress%2Cformat&ixlib=php-3.3.1', 
    type: 'CITADINE',
    details: [
      { label: '07/2019', value: '' },
      { label: '70 000 Km', value: '' },
      { label: 'Occasion', value: '' },
      { label: '8 CV', value: '' },
      { label: 'Consommation', value: '5,0/100 Km' },
      { label: 'Jaune', value: '' },
      { label: 'Boite manuelle', value: '' },
      { label: '100 CH', value: '' },
      { label: 'Nombre de portes', value: '2/3' },
      { label: 'Essence', value: '' },
      { label: 'Matricule', value: 'F 57' },
      { label: 'Jantes', value: '15' },
    ],
    rating: 4,
    actions: ['eye', 'p', 'exchange'],
  },
  {
    id: 10,
    name: 'MERCEDES CLASSE C',
    date: '02/11/2020',
    price: '550 000 DH',
    location: 'CASA',
    cityName: 'Casablanca',
    postalCode: '20000',
    seller: 'Particulier',
    image: 'https://mkt-vehicleimages-prd.autotradercdn.ca/photos/chrome/Expanded/White/2025MBC890001/2025MBC89000101.jpg',
    type: 'BERLINE',
    details: [
      { label: '12/2016', value: '' },
      { label: '120 000 Km', value: '' },
      { label: 'Occasion', value: '' },
      { label: '20 CV', value: '' },
      { label: 'Consommation', value: '5,8/100 Km' },
      { label: 'Noir', value: '' },
      { label: 'Boite automatique', value: '' },
      { label: '300 CH', value: '' },
      { label: 'Nombre de portes', value: '4/5' },
      { label: 'Diesel', value: '' },
      { label: 'Matricule', value: 'G 99' },
      { label: 'Jantes', value: '19' },
    ],
    rating: 5,
    actions: ['eye', 'p', 'exchange'],
  },
];
